MVC2/Controllers/CityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Airport.Core.Extensions;
using Airport.Core.Interfaces.Managers;
using Microsoft.Ajax.Utilities;
using MVC2.Models.Cities;

namespace MVC2.Controllers
{
    public class CityController : Controller
    {
        private readonly ICityManager _cityManager;

        public CityController(ICityManager cityManager)
        {
            _cityManager = cityManager;
        }

        // GET: Cities 
        public ActionResult Index()
        {
            ViewBag.IsAdmin = User.IsInRole("Admin");
            var cities = _cityManager.GetAllCities();
            return View(cities);
        }
        [HttpGet]
        public ActionResult AddNewCity()
        {
            return View("CityDetails",new CityModel());
        }
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult AddNewCity(CityModel city)
        {
            ValidateCityName(city);

            if (ModelState.IsValid)
            {
                _cityManager.AddCity(city.CityName);
                return RedirectToAction("Index");
            }
            return View("CityDetails",city);
        }

        public ActionResult EditCity(int cityid)
        {
            var city = _cityManager.GetCityById(cityid);
            var model = new CityModel
            {
                CityId = city.CityId,
                CityName = city.CityName
            };

            return View("CityDetails", model);
        }

        public ActionResult DeleteCity(int cityId)
        {
            ViewBag.IsAdmin = User.IsInRole("Admin");
            _cityManager.DeleteCity(cityId);
            var cities = _cityManager.GetAllCities();
            return View("Index", cities);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult EditCity(CityModel city)
        {
            ValidateCityName(city);
            if (ModelState.IsValid)
            {
                _cityManager.EditCity(city.CityId,city.CityName);
                return RedirectToAction("Index");
            }
            return View("CityDetails", city);
        }

        private void ValidateCityName(CityModel city)
        {
            city.CityName = city.CityName.Trim();
            //TODO(Done): get charArray and search char.IsLetter() , '-', ', ' '
            var nonLetter = false;
            var resolvedSymbols = new []{ '-', '\'', ' ' };

            if (string.IsNullOrEmpty(city.CityName) || !char.IsLetter(city.CityName[0]))
            {
                ModelState.AddModelError("CityName", "The city name must begin with a letter");
                return;
            }
            foreach (var itm in city.CityName.ToCharArray())
            {
                if (!char.IsLetter(itm) && !resolvedSymbols.Contains(itm))
                {
                    nonLetter = true;
                    break;
                }
            }
            if (nonLetter)
            {
                ModelState.AddModelError("CityName", @"The city name can consist only of letters, whitespaces, signs - and '");
            }
            //TODO(Done): ToProperCase() ext method
            city.CityName = city.CityName.ToProperCase();
            // unique cityName
            if (!string.IsNullOrEmpty(city.CityName))
            {
                var record = _cityManager.GetAllCities().FirstOrDefault(x =>
                    string.Equals(x.CityName, city.CityName, StringComparison.InvariantCultureIgnoreCase));
                if (record != null) ModelState.AddModelError(nameof(city.CityName), $"We already have {city.CityName} in DB");
            }
        }
    }
}

MVC2/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Airport.Core.Extensions;
using Airport.Core.Interfaces.Managers;
using Airport.Core.Interfaces.Repositories;
using Airport.Core.Models;
using MVC2.Models.Companies;


namespace MVC2.Controllers
{
    public class CompanyController : Controller
    {
        private readonly ICompanyManager _companyManager;
        //private readonly ICityManager _cityManager;
        private readonly ICityRepository _cityRepository;
        private readonly List<City> _cities;

        public CompanyController(ICompanyManager companyManager, ICityRepository cityRepository)
        {
            _companyManager = companyManager;
            _cityRepository = cityRepository;
            _cities = _cityRepository.SelectAll().ToList<City>();
        }

        // GET: Companies
        //[OutputCache(Duration = 300)] // 5 minutes
        public ActionResult Index()
        {
            ViewBag.IsAdmin = User.IsInRole("Admin");
            var companies = _companyManager.GetAllCompanies();
            return View(companies);
        }

        public ActionResult AddNewCompany()
        {
            var model = new CompanyModel
            {
                Cities = _cities
            };

            return View("CompanyDetails", model);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult AddNewCompany(CompanyModel company)
        {
            ValidateCompanyName(company);
            if (!string.IsNullOrEmpty(company.CompanyName))
            {
                var record = _companyManager.GetAllCompanies().FirstOrDefault(x =>
                    string.Equals(x.CompanyName, company.CompanyName, StringComparison.InvariantCultureIgnoreCase));
                if (record != null) ModelState.AddModelError(nameof(company.CompanyName), $"We already have {company.CompanyName} in DB");
            }
            if (ModelState.IsValid)
            {
                _companyManager.AddCompany(company.CompanyName, company.SelectedCityId);
                return RedirectToAction("Index");
            }
            company.Cities = _cities;
            return View("CompanyDetails", company);
        }

        public ActionResult DeleteCompany(int companyId)
        {
            ViewBag.IsAdmin = User.IsInRole("Admin");
            _companyManager.DeleteCompany(companyId);
            var companies = _companyManager.GetAllCompanies();
            return View("Index", companies);
        }

        public ActionResult EditCompany(int companyId)
        {
            var model = GetModel(companyId);
            return View("CompanyDetails", model);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult EditCompany(CompanyModel company)
        {
                ValidateCompanyName(company);
            if (ModelState.IsValidField("CompanyName"))
            {
                _companyManager.EditCompany(company.CompanyId, company.CompanyName, company.SelectedCityId);
                return RedirectToAction("Index");
            }
            company.Cities = _cityRepository.SelectAll().ToList<City>();
            return View("CompanyDetails",company);
        }

        public ActionResult CompanyPreview(int companyid)
        {
            var model = GetModel(companyid);
            return PartialView(model);
        }

        private CompanyModel GetModel(int companyId)
        {
            var company = _companyManager.GetCompanyById(companyId);
            var model = new CompanyModel
            {
                CompanyId = company.CompanyId,
                CompanyName = company.CompanyName,
                Cities = _cities,
                SelectedCityId = company.CityId,
                SelectedCityName = _cities.FirstOrDefault(x => x.CityId == company.CityId)?.CityName ?? ""
            };

            return model;
        }

        private void ValidateCompanyName(CompanyModel company)
        {
            company.CompanyName = company.CompanyName.Trim();
            //TODO(Done): get charArray and search char.IsLetter() , '-', ', ' '
            var nonLetter = false;
            var resolvedSymbols = new char[] { '-', '\'', ' ' };

            if (string.IsNullOrEmpty(company.CompanyName) || !char.IsLetter(company.CompanyName[0]))
            {
                ModelState.AddModelError("CompanyName", "The company name must begin with a letter");
                return;
            }
            foreach (var itm in company.CompanyName.ToCharArray())
            {
                if (!char.IsLetter(itm) && !resolvedSymbols.Contains(itm))
                {
                    nonLetter = true;
                    break;
                }
            }
            if (nonLetter)
            {
                ModelState.AddModelError("CompanyName", @"The company name can consist only of letters, whitespaces, signs - and '");
            }
            //TODO(Done): ToProperCase() ext method
            company.CompanyName = company.CompanyName.ToProperCase();          
        }
    }
}

MVC2/Controllers/FlightController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Airport.Core.Enums;
using Airport.Core.Interfaces.Managers;
using Airport.Core.Interfaces.Repositories;
using Airport.Core.Models;
using MVC2.Models.Flights;

namespace MVC2.Controllers
{
    public class FlightController : Controller
    {
        private readonly IFlightManager _flightManager;
        private readonly ICompanyRepository _companyRepository;
        private readonly ICityRepository _cityRepository;
        private readonly ITerminalRepository _terminalRepository;
        private readonly List<Company> _companies;
        private readonly List<City> _cities;
        private readonly List<Terminal> _terminals;

        public FlightController(IFlightManager flightManager, ICompanyRepository companyRepository, ICityRepository cityRepository, ITerminalRepository terminalRepository)
        {
            _flightManager = flightManager;
            _companyRepository = companyRepository;
            _cityRepository = cityRepository;
            _terminalRepository = terminalRepository;
            _companies = _companyRepository.SelectAll().OrderBy(x => x.CompanyName).ToList();
            _cities = _cityRepository.SelectAll().OrderBy(x => x.CityName).ToList();
            _terminals = _terminalRepository.SelectAll().OrderBy(x => x.TerminalName).ToList();
        }
        // GET: Flight
        public ActionResult Index()
        {
            ViewBag.IsAdmin = User.IsInRole("Admin");
            var flights = _flightManager.GetAllFlights();
            return View(flights);
        }

        public ActionResult DeleteFlight(int flightId)
        {
            ViewBag.IsAdmin = User.IsInRole("Admin");
            _flightManager.DeleteFlight(flightId);
            var flights = _flightManager.GetAllFlights();
            return View("Index", flights);
        }

        public ActionResult EditFlight(int flightid)
        {
            var model = GetModel(flightid);
            return View("FlightDetails", model);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult EditFlight(FlightModel flight)
        {
            ValidateFlight(flight);
            if (ModelState.IsValid)
            {
                var flightStatusEnum = (int)flight.FlightStatusId;
                //new DateTime(2018,02,20,20,40,00)
                // convert datetime2 to datetime

                var date = new DateTime(flight.FilghtDateTime.Year, flight.FilghtDateTime.Month, flight.FilghtDateTime.Day,
                    flight.FilghtDateTime.Hour, flight.FilghtDateTime.Minute, 0);

                _flightManager.EditFlight(flight.FlightId, flight.FlightNumber, date, flight.FlightDuration,
                    flightStatusEnum, flight.SelectedCityFrom, flight.SelectedCityTo, flight.SelectedCompanyId,
                    flight.SelectedTerminalId);
                return RedirectToAction("Index");
            }
            flight.Terminal = _terminals;
            flight.City = _cities;
            flight.Company = _companies;
            return View("FlightDetails", flight);
        }

        public ActionResult AddNewFlight()
        {
            var model = new FlightModel
            {
                Company = _companies,
                City = _cities,
                Terminal = _terminals,
            };
            return View("FlightDetails", model);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult AddNewFlight(FlightModel flight)
        {
            ValidateFlight(flight);
            if (!string.IsNullOrEmpty(flight.FlightNumber))
            {
                var record = _flightManager.GetAllFlights().FirstOrDefault(x =>
                    string.Equals(x.FlightNumber, flight.FlightNumber, StringComparison.InvariantCultureIgnoreCase));
                if (record != null) ModelState.AddModelError(nameof(flight.FlightNumber), $"We already have {flight.FlightNumber} in DB");
            }
            if (ModelState.IsValid)
            {
                var flightStatusEnum = (int)flight.FlightStatusId;
                //new DateTime(2018,02,20,20,40,00)
                // convert datetime2 to datetime

                var date = new DateTime(flight.FilghtDateTime.Year, flight.FilghtDateTime.Month, flight.FilghtDateTime.Day,
                    flight.FilghtDateTime.Hour, flight.FilghtDateTime.Minute, 0);

                _flightManager.AddFlight(flight.FlightNumber, date, flight.FlightDuration,
                    flightStatusEnum, flight.SelectedCityFrom, flight.SelectedCityTo, flight.SelectedCompanyId,
                    flight.SelectedTerminalId);
                return RedirectToAction("Index");
            }
            flight.Terminal = _terminals;
            flight.City = _cities;
            flight.Company = _companies;
            return View("FlightDetails", flight);
        }

        private void ValidateFlight(FlightModel flight)
        {
            //FlightNumber validation
            flight.FlightNumber = flight.FlightNumber.Trim();
            flight.FlightNumber = flight.FlightNumber.Replace(" ", "");
            flight.FlightNumber = flight.FlightNumber.ToUpper();

            //DateTime validation
            if (flight.FilghtDateTime < DateTime.Now)
            {
                ModelState.AddModelError(nameof(flight.FilghtDateTime), "Selected date and time should not be posted yesterday or later");
            }

            //FlightDuration validation
            var hoursAndMinutes = flight.FlightDuration.Split(':');
            if (hoursAndMinutes[0].StartsWith("00"))
            {
                ModelState.AddModelError(nameof(flight.FlightDuration),
                    "Minimum flight time is not less than 1 hour");
            }
            if (hoursAndMinutes[0].Length == 1)
            {
                flight.FlightDuration = flight.FlightDuration.Insert(0,"0");
            }

            if (hoursAndMinutes[1].Length == 1)
            {
                flight.FlightDuration = flight.FlightDuration + "0";
            }

            var hours = int.Parse(hoursAndMinutes[0]);
            var minutes = int.Parse(hoursAndMinutes[1]);

            if (hours >= 22 & minutes > 40)
            {
                ModelState.AddModelError(nameof(flight.FlightDuration), "The longest at the moment non-stop flight is not more than 22 hours 40 minutes");
            }

            // Departure/Arrival point validation

            if (flight.SelectedCityFrom == flight.SelectedCityTo)
            {
                ModelState.AddModelError(nameof(flight.SelectedCityTo), "The cities of departure and arrival can not be the same");
            }



        }

        private FlightModel GetModel(int flightId)
        {
            var flight = _flightManager.GetFlightById(flightId);
            var model = new FlightModel
            {
                FlightId = flight.FlightId,
                Terminal = _terminals,
                City = _cities,
                Company = _companies,
                FilghtDateTime = flight.FilghtDateTime,
                FlightDuration = flight.FlightDuration,
                FlightNumber = flight.FlightNumber,
                FlightStatusId = (FlightStatusEnum)flight.FlightStatusId,
                SelectedCityFrom = flight.CityFromId,
                SelectedCityTo = flight.CityToId,
                SelectedTerminalId = flight.TerminalId,
                SelectedCompanyId = flight.CompanyId,
                //SelectedCityName = _cities.FirstOrDefault(x => x.CityId == company.CityId)?.CityName ?? ""
            };

            return model;
        }
    }
}

MVC2/Views/Shared/_AdminLteBreadcrumb.cshtml
@* 
 This breadcrumb partial is meant to be dropped into the top of the main content page
    and uses the AdminLte.Breadcrumb class to dynamically build the breadcrumb per page
*@

@if (ViewBag.Breadcrumb != null)
{
    <ol class="breadcrumb">
        @foreach (Crumb crumb in ViewBag.Breadcrumb)
        {
            <li>
                @if (crumb.HasLink)
                {
                    <a href="@crumb.Link">
                        @if (crumb.HasIcon)
                        {
                            <i class="fa @crumb.Icon"></i>
                        }

                        <span>@crumb.Text</span>
                    </a>
                }
                else
                {
                    if (crumb.HasIcon)
                    {
                        <i class="fa @crumb.Icon"></i>
                    }

                    <span>@crumb.Text</span>
                }
            </li>
        }
    </ol>
}

MVC2/Views/Shared/_AdminLteLeftMenu.cshtml
@*
    This partial controls the left menu of the AdminLTE dashboard and is called automatically by _AdminLteLayout
       This is where you can add, modify, or remove navigation options in your app
       TODO: This preserves the links as-is for the demo, which lead to broken pages!
       It's up to you to make sure these links either get deleted or lead somewhere REAL!
*@


@{
    Layout = null;
}
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        @*<div class="user-panel">
            <div class="pull-left image">
                @if (User.IsInRole("Admin"))
                {
                    <img src="/Content/AdminLTE/img/admin-2-128x128.png" class="img-circle" alt="User Image" />
                }
                else
                {
                    <img src="/Content/AdminLTE/img/user-2-128x128.png" class="img-circle" alt="User Image" />
                }

            </div>
            <div class="pull-left info">
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>*@
        <!-- search form -->
        @*<form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search..." />
                <span class="input-group-btn">
                    <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
                </span>
            </div>
        </form>*@
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu">
            <li class="header">MAIN NAVIGATION</li>
            <li class="active treeview">
                <a href="#">
                    <i class="fa fa-dashboard"></i> <span>Dashboard</span> <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li>@Html.ActionLink("Flights", "Index", "Flight", null, new { @class = "menu-link" })</li>
                    <li>@Html.ActionLink("Cities", "Index", "City", null, new { @class = "menu-link" })</li>
                    <li>@Html.ActionLink("Terminals", "Index", "Terminal", null, new { @class = "menu-link" })</li>
                    <li>@Html.ActionLink("Persons", "Index", "CompanyPerson", null, new { @class = "menu-link" })</li>
                    <li>@Html.ActionLink("Companies", "Index", "Company", null, new { @class = "menu-link" })</li>
                </ul>
            </li>
            @*<li class="treeview">
            <a href="#">
                <i class="fa fa-files-o"></i>
                <span>Layout Options</span>
                <span class="label label-primary pull-right">4</span>
            </a>
            <ul class="treeview-menu">
                <li><a href="pages/layout/top-nav.html"><i class="fa fa-circle-o"></i> Top Navigation</a></li>
                <li><a href="pages/layout/boxed.html"><i class="fa fa-circle-o"></i> Boxed</a></li>
                <li><a href="pages/layout/fixed.html"><i class="fa fa-circle-o"></i> Fixed</a></li>
                <li><a href="pages/layout/collapsed-sidebar.html"><i class="fa fa-circle-o"></i> Collapsed Sidebar</a></li>
            </ul>
        </li>
        <li>
                <a href="pages/widgets.html">
                    <i class="fa fa-th"></i> <span>Widgets</span> <small class="label pull-right bg-green">new</small>
                </a>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-pie-chart"></i>
                    <span>Charts</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="pages/charts/morris.html"><i class="fa fa-circle-o"></i> Morris</a></li>
                    <li><a href="pages/charts/flot.html"><i class="fa fa-circle-o"></i> Flot</a></li>
                    <li><a href="pages/charts/inline.html"><i class="fa fa-circle-o"></i> Inline charts</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-laptop"></i>
                    <span>UI Elements</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="pages/UI/general.html"><i class="fa fa-circle-o"></i> General</a></li>
                    <li><a href="pages/UI/icons.html"><i class="fa fa-circle-o"></i> Icons</a></li>
                    <li><a href="pages/UI/buttons.html"><i class="fa fa-circle-o"></i> Buttons</a></li>
                    <li><a href="pages/UI/sliders.html"><i class="fa fa-circle-o"></i> Sliders</a></li>
                    <li><a href="pages/UI/timeline.html"><i class="fa fa-circle-o"></i> Timeline</a></li>
                    <li><a href="pages/UI/modals.html"><i class="fa fa-circle-o"></i> Modals</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-edit"></i> <span>Forms</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="pages/forms/general.html"><i class="fa fa-circle-o"></i> General Elements</a></li>
                    <li><a href="pages/forms/advanced.html"><i class="fa fa-circle-o"></i> Advanced Elements</a></li>
                    <li><a href="pages/forms/editors.html"><i class="fa fa-circle-o"></i> Editors</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-table"></i> <span>Tables</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="pages/tables/simple.html"><i class="fa fa-circle-o"></i> Simple tables</a></li>
                    <li><a href="pages/tables/data.html"><i class="fa fa-circle-o"></i> Data tables</a></li>
                </ul>
            </li>
            <li>
                <a href="pages/calendar.html">
                    <i class="fa fa-calendar"></i> <span>Calendar</span>
                    <small class="label pull-right bg-red">3</small>
                </a>
            </li>
            <li>
                <a href="pages/mailbox/mailbox.html">
                    <i class="fa fa-envelope"></i> <span>Mailbox</span>
                    <small class="label pull-right bg-yellow">12</small>
                </a>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-folder"></i> <span>Examples</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="pages/examples/invoice.html"><i class="fa fa-circle-o"></i> Invoice</a></li>
                    <li><a href="pages/examples/login.html"><i class="fa fa-circle-o"></i> Login</a></li>
                    <li><a href="pages/examples/register.html"><i class="fa fa-circle-o"></i> Register</a></li>
                    <li><a href="pages/examples/lockscreen.html"><i class="fa fa-circle-o"></i> Lockscreen</a></li>
                    <li><a href="pages/examples/404.html"><i class="fa fa-circle-o"></i> 404 Error</a></li>
                    <li><a href="pages/examples/500.html"><i class="fa fa-circle-o"></i> 500 Error</a></li>
                    <li><a href="pages/examples/blank.html"><i class="fa fa-circle-o"></i> Blank Page</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-share"></i> <span>Multilevel</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
                    <li>
                        <a href="#"><i class="fa fa-circle-o"></i> Level One <i class="fa fa-angle-left pull-right"></i></a>
                        <ul class="treeview-menu">
                            <li><a href="#"><i class="fa fa-circle-o"></i> Level Two</a></li>
                            <li>
                                <a href="#"><i class="fa fa-circle-o"></i> Level Two <i class="fa fa-angle-left pull-right"></i></a>
                                <ul class="treeview-menu">
                                    <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                                    <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
                </ul>
            </li>
            <li><a href="documentation/index.html"><i class="fa fa-book"></i> Documentation</a></li>
            <li class="header">LABELS</li>
            <li><a href="#"><i class="fa fa-circle-o text-danger"></i> Important</a></li>
            <li><a href="#"><i class="fa fa-circle-o text-warning"></i> Warning</a></li>
            <li><a href="#"><i class="fa fa-circle-o text-info"></i> Information</a></li>*@
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>

MVC2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @RenderSection("styles", required: false)

    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Airport panel", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
	                <li>@Html.ActionLink("Companies", "Index", "Company")</li>
	                <li>@Html.ActionLink("Cities", "Index", "City")</li>
	                <li>@Html.ActionLink("Terminals", "Index", "Terminal")</li>
	                <li>@Html.ActionLink("Flights", "Index", "Flight")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>