MVC2/Models/CompanyPersons/CompanyPersonModel.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Airport.Core.Models;

namespace MVC2.Models.CompanyPersons
{
    public class CompanyPersonModel
    {
        public int PersonId { get; set; }

        [MinLength(2, ErrorMessage = "The length must be more than 2")]
        [DisplayName("First Name")]
        [Required(ErrorMessage = "Field can't be empty")]
        public string FirstName { get; set; }

        [MinLength(2, ErrorMessage = "The length must be more than 2")]
        [DisplayName("Last Name")]
        [Required(ErrorMessage = "Field can't be empty")]
        public string LastName { get; set; }

        [DisplayName("Phone")]
        [Phone]
        [DataType(DataType.PhoneNumber, ErrorMessage = "Provided phone number not valid")]
        [Required(ErrorMessage = "Your must provide a Phone Number")]
        public string Telephone { get; set; }

        [Display(Name = "Email address")]
        [EmailAddress]
        [Required(ErrorMessage = "Field can't be empty")]
        [DataType(DataType.EmailAddress, ErrorMessage = "E-mail is not valid")]
        public string Email { get; set; }

        public int SelectedCompanyId { get; set; }

        [DisplayName("Company")]
        public string SelectedCompanyName { get; set; }

        [DisplayName("Companies")]
        public List<Company> Companies { get; set; }
    }
}

MVC2/Controllers/CompanyPersonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Airport.Core.Extensions;
using Airport.Core.Interfaces.Managers;
using Airport.Core.Interfaces.Repositories;
using Airport.Core.Models;
using MVC2.Models.CompanyPersons;

namespace MVC2.Controllers
{
    public class CompanyPersonController : Controller
    {
        private readonly ICompanyPersonManager _companyPersonManager;
        private readonly ICompanyRepository _companyPersonRepository;
        private readonly List<Company> _companies;

        public CompanyPersonController(ICompanyPersonManager companyPersonManager, ICompanyRepository companyPersonRepository)
        {
            _companyPersonManager = companyPersonManager;
            _companyPersonRepository = companyPersonRepository;
            _companies = _companyPersonRepository.SelectAll().OrderBy(x => x.CompanyName).ToList();
        }

        // GET: CompanyPerson
        public ActionResult Index()
        {
            ViewBag.IsAdmin = User.IsInRole("Admin");
            var persons = _companyPersonManager.GetAllCompanyPersons();
            return View(persons);
        }

        public ActionResult AddNewCompanyPerson()
        {
            var model = new CompanyPersonModel()
            {
                Companies = _companies
            };
            return View("CompanyPersonDetails", model);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult AddNewCompanyPerson(CompanyPersonModel person)
        {
            ValidateCompanyPerson(person);
            if (!string.IsNullOrEmpty(person.FirstName) && !string.IsNullOrEmpty(person.LastName) && person.SelectedCompanyId!=0)
            {
                var record = _companyPersonManager.GetAllCompanyPersons().FirstOrDefault(x => string.Equals(x.FirstName, person.FirstName,
                                                                                                    StringComparison.InvariantCultureIgnoreCase) &&
                                                                                                string.Equals(x.LastName, person.LastName,
                                                                                                    StringComparison.InvariantCultureIgnoreCase) &&
                                                                                                x.CompanyId == person.SelectedCompanyId);
                if (record != null) ModelState.AddModelError(nameof(person.LastName), $"We already have {person.FirstName} {person.LastName}" +
                                                                                      $" for selected company in DB");
            }
            //TODO: ValidatePersonName
            if (ModelState.IsValid)
            {
                _companyPersonManager.AddCompanyPerson(person.FirstName, person.LastName, person.Telephone,
                    person.Email, person.SelectedCompanyId);
                return RedirectToAction("Index");
            }
            person.Companies = _companies;
            return View("CompanyPersonDetails", person);
        }

        public ActionResult DeleteCompanyPerson(int presonId)
        {
            ViewBag.IsAdmin = User.IsInRole("Admin");
            _companyPersonManager.DeleteCompanyPerson(presonId);
            var presons = _companyPersonManager.GetAllCompanyPersons();
            return View("Index", presons);
        }

        public ActionResult EditCompanyPerson(int personId)
        {
            var model = GetModel(personId);
            return View("CompanyPersonDetails", model);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult EditCompanyPerson(CompanyPersonModel person)
        {
            ValidateCompanyPerson(person);
            if (ModelState.IsValid)
            {
                _companyPersonManager.EditCompanyPerson(person.PersonId, person.FirstName, person.LastName, person.Telephone, person.Email, person.SelectedCompanyId);
                return RedirectToAction("Index");
            }
            person.Companies = _companyPersonRepository.SelectAll().ToList<Company>();
            return View("CompanyPersonDetails", person);
        }

        public ActionResult CompanyPersonPreview(int personId)
        {
            var model = GetModel(personId);
            return PartialView(model);
        }

        private CompanyPersonModel GetModel(int personId)
        {
            var person = _companyPersonManager.GetCompanyPersonById(personId);
            var model = new CompanyPersonModel
            {
                PersonId = person.PersonId,
                FirstName = person.FirstName,
                LastName = person.LastName,
                Email = person.Email,
                Telephone = person.Telephone,
                Companies = _companies,
                SelectedCompanyId = person.CompanyId,
                SelectedCompanyName = _companies.FirstOrDefault(x => x.CompanyId == person.CompanyId)?.CompanyName ?? ""
            };
            return model;
        }

        private void ValidateCompanyPerson(CompanyPersonModel person)
        {
            person.FirstName = person.FirstName.Trim();
            //TODO(Done): get charArray and search char.IsLetter() , '-', ', ' '
            var nonLetter = false;
            var resolvedSymbols = new char[] { '-', '\'', ' ' };

            if (string.IsNullOrEmpty(person.FirstName) || !char.IsLetter(person.FirstName[0]))
            {
                ModelState.AddModelError("FirstName", "The first name must begin with a letter");
                return;
            }
            foreach (var itm in person.FirstName.ToCharArray())
            {
                if (!char.IsLetter(itm) && !resolvedSymbols.Contains(itm))
                {
                    nonLetter = true;
                    break;
                }
            }
            if (nonLetter)
            {
                ModelState.AddModelError("FirstName", @"The first name can consist only of letters, whitespaces, signs - and '");
            }
            //TODO(Done): ToProperCase() ext method
            person.FirstName = person.FirstName.ToProperCase();

            if (string.IsNullOrEmpty(person.LastName) || !char.IsLetter(person.LastName[0]))
            {
                ModelState.AddModelError("LastName", "The first name must begin with a letter");
                return;
            }
            foreach (var itm in person.LastName.ToCharArray())
            {
                if (!char.IsLetter(itm) && !resolvedSymbols.Contains(itm))
                {
                    nonLetter = true;
                    break;
                }
            }
            if (nonLetter)
            {
                ModelState.AddModelError("LastName", @"The first name can consist only of letters, whitespaces, signs - and '");
            }
            //TODO(Done): ToProperCase() ext method
            person.LastName = person.LastName.ToProperCase();
        }
    }
}

MVC2/Views/CompanyPerson/CompanyPersonDetails.cshtml
@model  MVC2.Models.CompanyPersons.CompanyPersonModel

@{
    var action = Model.PersonId > 0 ? "EditCompanyPerson" : "AddNewCompanyPerson";
    var header = Model.PersonId > 0 ? "Edit person" : "Add new person";
    var buttonText = Model.PersonId > 0 ? "Save" : "Create";
    ViewBag.Title = "Persons";
}

<div class="container body-content" style="padding-top: 20px;">
    @using (Html.BeginForm(action, "CompanyPerson", FormMethod.Post, new { @class = "form-horizontal col-md-offset-3", role = "form" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4 class="col-md-offset-3">@header</h4>
            <hr/>
            @Html.ValidationSummary(true, "", new {@class = "text-danger"})

            @Html.HiddenFor(x => x.PersonId)

            <div class="form-group">
                @Html.LabelFor(model => model.FirstName, htmlAttributes: new {@class = "control-label col-md-2"})
                <div class="col-md-10" style="margin-bottom: 10px">
                    @Html.EditorFor(model => model.FirstName, new {htmlAttributes = new {@class = "form-control"}})
                    @Html.ValidationMessageFor(model => model.FirstName, "", new {@class = "text-danger"})
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.LastName, htmlAttributes: new {@class = "control-label col-md-2"})
                <div class="col-md-10" style="margin-bottom: 10px">
                    @Html.EditorFor(model => model.LastName, new {htmlAttributes = new {@class = "form-control"}})
                    @Html.ValidationMessageFor(model => model.LastName, "", new {@class = "text-danger"})
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Telephone, htmlAttributes: new {@class = "control-label col-md-2"})
                <div class="col-md-10" style="margin-bottom: 10px">
                    @Html.EditorFor(model => model.Telephone, new {htmlAttributes = new {@class = "form-control"}})
                    @Html.ValidationMessageFor(model => model.Telephone, "", new {@class = "text-danger"})
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new {@class = "control-label col-md-2"})
                <div class="col-md-10" style="margin-bottom: 10px">
                    @Html.EditorFor(model => model.Email, new {htmlAttributes = new {@class = "form-control"}})
                    @Html.ValidationMessageFor(model => model.Email, "", new {@class = "text-danger"})
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Companies, htmlAttributes: new {@class = "control-label col-md-2"})
                @*<div class="form-group">*@
                <div class="col-md-10" style="margin-bottom: 10px">
                    @*<div style="margin-right: 80px">@Html.LabelFor(model => model.Companies, htmlAttributes: new { @class = "control-label col-md-2" })</div>*@
                    <select name="SelectedCompanyId" id="SelectedCompanyId" class="form-control" placeholder="Select company">
                        @foreach (var itm in Model.Companies)
                        {
                            if (Model.SelectedCompanyId == itm.CompanyId)
                            {
                                <option name="Company" value="@itm.CompanyId" selected>@itm.CompanyName</option>
                            }
                            else
                            {
                                <option name="Company" value="@itm.CompanyId">@itm.CompanyName</option>
                            }
                        }
                    </select>
                </div>
            </div>
                <div class="form-group">
                    <div class="col-md-offset-3 col-md-2" style="text-align: center;">
                        <input type="submit" value="@buttonText" class="btn btn-primary" style="width: 75px;"/>
                    </div>
                </div>
            </div>
    }
    <div style="text-align: center;margin-left: -10px;">
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

MVC2/Views/CompanyPerson/CompanyPersonPreview.cshtml
@model MVC2.Models.CompanyPersons.CompanyPersonModel

<div data-companyPersonId="@Model.SelectedCompanyId" class="companyPerson-preview">
    <div class="form-group row">
        @Html.LabelFor(model => model.SelectedCompanyName, htmlAttributes: new { @class = "control-label col-md-4" })
        <div class="col-md-8">
            @Html.DisplayFor(model => model.SelectedCompanyName, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(model => model.Telephone, htmlAttributes: new { @class = "control-label col-md-4" })
        <div class="col-md-8">
            @Html.DisplayFor(model => model.Telephone, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>
</div>

MVC2/Views/CompanyPerson/Index.cshtml
@model Airport.Core.Models.CompanyPerson[]

@{
    ViewBag.Title = "Company Persons";
    var isAdmin = ViewBag.IsAdmin;
}

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Persons Table</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="persons" class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>First Name</th>
                                <th>Last Name</th>
                                <th>Phone</th>
                                <th>Email</th>
                                @if (isAdmin)
                                {
                                    <th>Actions</th>
                                }
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var itm in Model)
                            {
                                <tr id="personId-@itm.PersonId">
                                    <td>@itm.PersonId</td>
                                    <td>@itm.FirstName</td>
                                    <td>@itm.LastName</td>
                                    <td>@itm.Telephone</td>
                                    <td>@itm.Email</td>
                                    @if (isAdmin)
                                    {
                                        <td>
                                            <span>@Html.ActionLink("Edit", "EditCompanyPerson", new { presonId = itm.PersonId }, new { @class = "btn btn-primary btn-success btn-xs" })</span>
                                            <span>@Html.ActionLink("Delete", "DeleteCompanyPerson", new { presonId = itm.PersonId }, new { @class = "btn btn-primary btn-danger btn-xs" })</span>
                                        </td>
                                    }
                                </tr>
                            }
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>Id</th>
                                <th>First Name</th>
                                <th>Last Name</th>
                                <th>Phone</th>
                                <th>Email</th>
                                @if (isAdmin)
                                {
                                    <th>Actions</th>
                                }
                            </tr>
                        </tfoot>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            @if (isAdmin)
            {
                @Html.ActionLink("Add new preson", "AddNewCompanyPerson", routeValues: null, htmlAttributes: new { id = "AddLink", @class = "btn btn-primary", @style = "margin-left: 50%;transform: translateX(-50%);" })
            }
        </div>
    </div>
</section>

@section Scripts{
    <script>
        $(function () {
            $('#persons').DataTable({
                'paging': true,
                'lengthChange': false,
                'searching': false,
                'ordering': true,
                'info': true,
                'autoWidth': false
            });
        })
    </script>
}